# Generated by Django 5.1.3 on 2024-12-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        #migrations.AlterUniqueTogether(
            #name='review',
            #unique_together={('title','rating')},
       # ),
    ]
