# Generated by Django 5.1.3 on 2024-12-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together'),
    ]

    operations = [
        #migrations.AlterUniqueTogether(
            #name='review',
            #unique_together=set(),
        #),
    ]
