# Generated by Django 5.1.3 on 2025-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_department_alter_review_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
