# Generated by Django 5.1.3 on 2024-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_unique_together'),
    ]

    operations = [
          migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX review_content_idx ON reviews_review (content(255));",
            reverse_sql="DROP INDEX review_content_idx ON reviews_review;"
        ),
    ]
