# Generated by Django 5.1.3 on 2024-12-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
